### PR TITLE
Fix kanji date formatting (by using dateSkeletons instead of dateFormats)

### LINKED ISSUE #5806: Restore kanji date formatting
Due to a data bug in CLDR, semantic skeletons in ICU4X 2.0 resolve to the ASCII date formats instead of the kanji date formats for short length in Japanese. It would be nice if CLDR would resolve this in data.

Example test failure (currently ignored):

```
  left: "2023/12/22"
 right: "2023年12月22日"
```

The root cause also impacts other locales in smaller ways.

https://unicode-org.atlassian.net/browse/CLDR-14993

CC @pedberg @macchiati

### PR DESCRIPTION
**Pull request by Manishearth**
Fixes #5806

### CODE REVIEW

File: provider/source/src/datetime/neo_skeleton.rs [hunk 1]
```diff
@@ -319,9 +319,9 @@ fn gen_date_components(
     // <https://unicode-org.atlassian.net/browse/CLDR-14993>
     // TODO(#308): Utilize the numbering system pattern variations.
     let date_pattern: reference::Pattern = match length {
```
Comment (sffc) [inline provider/source/src/datetime/neo_skeleton.rs:321]: Nit: Remove the TODO on lines 312-317

File: provider/source/src/datetime/patterns.rs [hunk 2]
```diff
@@ -107,10 +107,10 @@ impl From<&cldr_serde::ca::Dates> for TimeLengths<'_> {
...
         let skeletons_v1 = DateSkeletonPatterns::from(&other.datetime_formats.available_formats);
 
-        let pattern_str_full = other.time_formats.full.get_pattern();
-        let pattern_str_long = other.time_formats.long.get_pattern();
-        let pattern_str_medium = other.time_formats.medium.get_pattern();
-        let pattern_str_short = other.time_formats.short.get_pattern();
+        let pattern_str_full = other.time_skeletons.full.get_pattern();
+        let pattern_str_long = other.time_skeletons.long.get_pattern();
+        let pattern_str_medium = other.time_skeletons.medium.get_pattern();
+        let pattern_str_short = other.time_skeletons.short.get_pattern();
```
Comment (sffc) [inline provider/source/src/datetime/patterns.rs:113]: Suggestion (optional, follow-up OK): This is a bit confusing since `TimeLengths` is only used for `preferred_hour_cycle`. I think there's another issue to clean this up. We should at least add a comment that the actual patterns here are not used anywhere any more.

File: provider/source/data/debug/datetime/BuddhistDateNeoSkeletonPatternsV1/m0d/es-AR.json [hunk 3]
```diff
@@ -12,6 +12,6 @@
   "elements": [
```
Comment (sffc) [inline provider/source/data/debug/datetime/BuddhistDateNeoSkeletonPatternsV1/m0d/es-AR.json:12]: Thought: The other payloads changed more than I would have expected. Please spot-check to make sure that the changes are an expected outcome of using datetimeSkeletons.

**Review by sffc — APPROVED** [review]

File: provider/source/src/datetime/mod.rs [hunk 4]
```diff
@@ -320,7 +320,7 @@ mod test {
 
         let cs_dates = DateLengths::from(&data);
```
Comment (sffc) [inline provider/source/src/datetime/mod.rs:321]: Thought: DateLengths and TimeLengths need to go. Maybe while you are in here you can get rid of them (can be in a follow-up).

Comment (Manishearth) [reply provider/source/src/datetime/mod.rs:321]: I don't know what it means to get rid of them; these are datetime datagen types.

File: provider/source/data/debug/datetime/BuddhistDateNeoSkeletonPatternsV1/m0d/es-AR.json (hunk 3 above)
Comment (Manishearth) [reply provider/source/data/debug/datetime/BuddhistDateNeoSkeletonPatternsV1/m0d/es-AR.json:12]: I'm not fully sure how to do this, I don't understand the fallback/resolution algorithm here. I could look this up, but I'd rather hand the baton on this issue back to you.

From what I can tell a lot of these changes are basically due to skeleton resolution happening (where previously it didn't happen becuase it used explicit formats). CLDR should potentially have some consistency checks here.

**Review by sffc — DISMISSED** [review]

**Comment by sffc** [comment]
https://unicode-org.atlassian.net/issues/CLDR-14993

File: provider/source/data/debug/datetime/GregorianDateNeoSkeletonPatternsV1/m0d/sr.json [hunk 5]
```diff
@@ -9,7 +10,8 @@
     0
   ],
   "elements": [
-    "d. MMMM",
+    "dd.MMMM",
+    "dd.MM.",
     "d. M."
   ]
```
[the remark this answers is not in the document]
Comment (Manishearth) [reply provider/source/data/debug/datetime/GregorianDateNeoSkeletonPatternsV1/m0d/sr.json]: thanks for following up!!

**Review by sffc — APPROVED** [review]
