### PR TITLE
Write the UTF-16 fast paths using raw pointers to work around a compiler regression

### LINKED ISSUE #6788: Work around bad codegen for the hottest loop in UTF-16 normalization
rustc generates bad code for the hottest loop in UTF-16 normalization, which makes ICU4X much slower than ICU4C when finding out the already-normalized prefix. (Previously, this particular loop formulation was found to be as fast as ICU4C's loop formulation for the situation that also writes to an output buffer. I haven't checked, yet, if writing makes a difference or if the compiler side has regressed since I last looked into the loop formulation.)

How the pointer advancement for a slice iterator compiles depends on things that logically are not supposed to have an effect on the output after optimization, yet they do. See https://github.com/rust-lang/rust/issues/144684 .

Look at the code on Compiler Explorer, try changing the things that affect the outcome per the above Rust issue and also try the suggestion from https://users.rust-lang.org/t/getting-rustc-to-allocate-a-particular-local-in-a-register/132391/6  until the bad codegen isn't triggered.

(Note: While this should fix perf for Latin-script input, it won't alone be enough for Greek, Chinese, etc. We should also make sure that the trie accessors are fully inlined as they are in ICU4C and make sure that trie access doesn't branch on trie type multiple times per lookup. See previously-filed issues about trie access perf.)

### PR DESCRIPTION
**Pull request by hsivonen**
The compiler regression is https://github.com/rust-lang/rust/issues/144684

This formulation does not restore `normalize_utf16_to` to ICU4C parity for English
(but still +46% throughput compared to without this changeset), but this does put
`split_normalized_utf16` from slower than ICU4C to faster than ICU4C for English
(+174% throughput compared to without this changeset).

Closes #6788

Draft PR to let #6816 land first.

### CODE REVIEW

**Comment by hsivonen** [comment]
Requesting review from @Manishearth per https://github.com/unicode-org/icu4x/issues/6788#issuecomment-3142096018

File: components/normalizer/src/lib.rs [hunk 1]
```diff
@@ -1976,9 +1976,27 @@ impl<'data> DecomposingNormalizerBorrowed<'data> {
             // detecting an internal bug without panic. (In debug builds, internal bugs panic instead.)
             #[expect(clippy::never_loop)]
             'fastwrap: loop {
-                let mut code_unit_iter = decomposition.delegate.as_slice().iter();
+                // Commented out `code_unit_iter` and used `ptr` and `end` to
+                // work around https://github.com/rust-lang/rust/issues/144684 .
+                //
+                // let mut code_unit_iter = decomposition.delegate.as_slice().iter();
```
Comment (echeran) [inline components/normalizer/src/lib.rs:1982]: here and below: Should we not just remove commented out code rather than leave it in? Usually not preferred to keep in for "code hygiene" reasons.

File: components/normalizer/src/lib.rs [hunk 2]
```diff
@@ -1999,9 +2017,19 @@ impl<'data> DecomposingNormalizerBorrowed<'data> {
                                 break 'surrogateloop;
                             }
                             if surrogate_base <= (0xDBFF - 0xD800) {
```
Comment (echeran) [inline components/normalizer/src/lib.rs:2019]: suggestion: Define constants for 0xDBFF, 0xD800, for readability? like {HIGH/LOW}_SURROGATE_{BEGIN,END,LIMIT}?

If not, then update the comments to explain the magic numbers.

File: components/normalizer/src/lib.rs (hunk 1 above)
Comment (hsivonen) [reply components/normalizer/src/lib.rs:1982]: I'm leaving this in, because it's useful to be able to easily (ctrl-/ or similar in an editor) flip this either way to see if the compiler has been fixed.

File: components/normalizer/src/lib.rs (hunk 2 above)
Comment (hsivonen) [reply components/normalizer/src/lib.rs:2019]: These numbers were not introduced in this changeset, so I'm treating this as part of #6835.

**Comment by hsivonen** [comment]
Thanks!
