### PR TITLE
Fix arithmetic in Indian calendar

### LINKED ISSUE #2476: Day-of-week calculation in Indian calendar appears broken
In Chrome:

```javascript
new Intl.DateTimeFormat("en-u-ca-indian", { dateStyle: "full" }).format(new Date())
// 'Monday, Bhadra 7, 1944 Saka'
```

But in ICU4X:

```rust
assert_eq!(
    "Friday, Bhadra 7, 1944 Saka",
    formatter.format_to_string(&Date::new_indian_date(1944, 6, 7).unwrap())
);
```

CC @zbraniecki @gregtatum @Manishearth

### PR DESCRIPTION
**Pull request by Manishearth**
Fixes #2476

I didn't bother to include day-of-week stuff in the test because day-of-week works by converting to iso first in all calendars, so testing the iso roundtrip is accurate is sufficient

I did test the testcases with ICU (Chrome)

### CODE REVIEW

**Review by robertbastian — DISMISSED** [review]

File: components/calendar/src/calendar_arithmetic.rs [hunk 1]
```diff
@@ -22,6 +22,30 @@ pub trait CalendarArithmetic: Calendar {
...
+        let months_in_year = Self::months_for_every_year(year);
+        let mut days: u32 = 0;
+        for month in 1..=months_in_year {
+            days += Self::month_days(year, month) as u32;
+        }
+        days
+    }
+
+    /// Set days_in_year to this for solar calendars
+    fn days_in_year_solar(year: i32) -> u32 {
```
Comment (sffc) [inline components/calendar/src/calendar_arithmetic.rs:42]: Nit: I don't like having this method here since it should not be called as part of the trait; it's only a convenience. I'd rather see solar calendars implement days_in_provided_year by calling `Iso::days_in_provided_year()` and putting the custom impl on `Iso`.

Comment (Manishearth) [reply components/calendar/src/calendar_arithmetic.rs:42]: They can't call the ISO one because ISO has different leap year rules. I'll just copy paste the implementations instead.

**Review by sffc — APPROVED** [review]

**Review by sffc — DISMISSED** [review]
LGTM but please merge in main and fix the broken test I added in the PR that created the issue:

https://github.com/unicode-org/icu4x/pull/2477/files#diff-f89d3af86d2af78dfb04ce8d443c96e4c69a4d75a010abdc490aea33ededdec1R288

**Review by sffc — APPROVED** [review]

**Comment by sffc** [comment]
Thank you!
