### PR TITLE
Never use fallback for baked segmentation data

### LINKED ISSUE #4489: Problem with `icu_segmenter` and `ICU4X_DATA_DIR`
bakeddata-scripts/main.rs has the following line:

```rust
        if component == "segmenter" {
            // segmenter uses hardcoded locales internally, so fallback is not necessary.
            driver.clone().with_fallback_mode(FallbackMode::Hybrid)
        } else {
            driver.clone()
        }
```

However, when customers generate custom compiled data via a manual invocation of icu4x-datagen and then use it via `ICU4X_DATA_DIR`, they don't get this condition, and end up generating baked segmenter data that uses fallback. This is exposed via the following compile error:

```
failed to resolve: could not find `locid_transform` in `icu`
could not find `locid_transform` in `icu`
segmenter_dictionary_w_auto_v1.rs.data(2, 5246158): Actual error occurred here
mod.rs(19, 1): consider importing this module: `use icu_locid_transform::fallback;
````

@robertbastian

### PR DESCRIPTION
**Pull request by robertbastian**
Fixes #4489

### CODE REVIEW

File: provider/datagen/src/driver.rs [hunk 1]
```diff
@@ -438,7 +438,7 @@ impl DatagenDriver {
 
             let transform_duration = instant1.elapsed();
 
-            if fallback == FallbackMode::Runtime {
+            if fallback == FallbackMode::Runtime && !key.path().get().starts_with("segmenter") {
```
Comment (sffc) [inline provider/datagen/src/driver.rs:441]:
```suggestion
            // TODO(#4511): Use auxiliary keys for segmenter fallback
            if fallback == FallbackMode::Runtime && !key.path().get().starts_with("segmenter/") {
```

**Review by sffc — DISMISSED** [review]

File: provider/datagen/src/driver.rs [hunk 2]
```diff
@@ -438,7 +438,9 @@ impl DatagenDriver {
 
             let transform_duration = instant1.elapsed();
 
-            if fallback == FallbackMode::Runtime {
+            // segmenter uses hardcoded locales internally, so fallback is not necessary.
+            // TODO(#4511): Use auxiliary keys for segmenter
+            if fallback == FallbackMode::Runtime && !key.path().get().starts_with("segmenter") {
```
Comment (sffc) [inline provider/datagen/src/driver.rs:443]: Optional
```suggestion
            if fallback == FallbackMode::Runtime && !key.path().get().starts_with("segmenter/") {
```

**Review by sffc — APPROVED** [review]
