### PR TITLE
week_of refactoring

### LINKED ISSUE #2421: Clean up the week_of module
There are a variety of cleanups that should be done in the week_of module, including:

- week_of: sclarify the docs since this module appears to support both month and year?
- simple_week_of: Does anyone actually need this? It's wrong for the ISO calendar.
- At least add an example to week_of.
- Previous year: is it possible to get week 54?

### PR DESCRIPTION
**Pull request by sffc**
Fixes #2421 (except FFI which I'll do later)

This makes the `week_of` module private and instead exports only select parts of it, as well as exposing the functionality via `Date`. It also moves the WeekDataV1 data struct into the icu_calendar crate.

### CODE REVIEW

File: components/calendar/src/week_of.rs [hunk 1]
```diff
@@ -221,20 +227,20 @@ pub fn simple_week_of(first_weekday: IsoWeekday, day: u16, week_day: IsoWeekday)
 
 #[cfg(test)]
 mod tests {
-    use super::{week_of, WeekOfYearConfigV1, RelativeUnit, RelativeWeek, UnitInfo, WeekOf};
+    use super::{week_of, WeekOfYearConfig, RelativeUnit, RelativeWeek, UnitInfo, WeekOf};
     use crate::{error::DateTimeError, types::IsoWeekday, Date, DateDuration};
 
-    static ISO_CALENDAR: WeekOfYearConfigV1 = WeekOfYearConfigV1 {
+    static ISO_CALENDAR: WeekOfYearConfig = WeekOfYearConfig {
```
Comment (Manishearth) [inline components/calendar/src/week_of.rs]: thought: perhaps this should be available as an associated const on `Iso`

**Review by Manishearth — APPROVED** [review]
praise: this seems much cleaner!
