### PR TITLE
Throw error in Date::try_from_fields for very large year values.

### LINKED ISSUE #7049: Attempted to multiply with overflow in chinese calendar construction code
I haven't even finished writing this fuzzer and  I found a bug

```
	FuzzInput {
	    year: 889192448,
	    month: 0,
	    day: 0,
	    month_interpretation: Ordinal,
	    overflow_constrain: false,
	    cal: Dangi,
	}

thread '<unnamed>' (1026981) panicked at components/calendar/src/cal/chinese/simple.rs:93:32:
attempt to multiply with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==1026981== ERROR: libFuzzer: deadly signal

```

Currently this just sets `year` and `day`, ignoring `month` entirely. I could clean this up into a proper testcase but i'd like to actually finished the fuzzer.

Fuzzer code:

<details>

```rust
#[derive(Arbitrary, Debug)]
struct FuzzInput {
    year: i32,
    month: u8,
    day: u8,
    month_interpretation: MonthInterpretation,
    overflow_constrain: bool,
    cal: AnyCalendarKind,
}

#[derive(Arbitrary, Debug)]
enum MonthInterpretation {
    Ordinal,
    CodeNormal,
    CodeLeap,
}

#[derive(Arbitrary, Debug)]
pub enum AnyCalendarKind {
    Buddhist,
    Chinese,
    Coptic,
    Dangi,
    Ethiopian,
    EthiopianAmeteAlem,
    Gregorian,
    Hebrew,
    Indian,
    HijriTabularTypeIIFriday,
    HijriSimulatedMecca,
    HijriTabularTypeIIThursday,
    HijriUmmAlQura,
    Iso,
    Japanese,
    JapaneseExtended,
    Persian,
    Roc,
}

impl From<AnyCalendarKind> for icu_calendar::AnyCalendarKind {
    fn from(other: AnyCalendarKind) -> Self {
        match other {
            AnyCalendarKind::Buddhist => Self::Buddhist,
            AnyCalendarKind::Chinese => Self::Chinese,
            AnyCalendarKind::Coptic => Self::Coptic,
            AnyCalendarKind::Dangi => Self::Dangi,
            AnyCalendarKind::Ethiopian => Self::Ethiopian,
            AnyCalendarKind::EthiopianAmeteAlem => Self::EthiopianAmeteAlem,
            AnyCalendarKind::Gregorian => Self::Gregorian,
            AnyCalendarKind::Hebrew => Self::Hebrew,
            AnyCalendarKind::Indian => Self::Indian,
            AnyCalendarKind::HijriTabularTypeIIFriday => Self::HijriTabularTypeIIFriday,
            AnyCalendarKind::HijriSimulatedMecca => Self::HijriSimulatedMecca,
            AnyCalendarKind::HijriTabularTypeIIThursday => Self::HijriTabularTypeIIThursday,
            AnyCalendarKind::HijriUmmAlQura => Self::HijriUmmAlQura,
            AnyCalendarKind::Iso => Self::Iso,
            AnyCalendarKind::Japanese => Self::Japanese,
            AnyCalendarKind::JapaneseExtended => Self::JapaneseExtended,
            AnyCalendarKind::Persian => Self::Persian,
            AnyCalendarKind::Roc => Self::Roc,
        }
    }
}

fuzz_target!(|data: FuzzInput| {
    let calendar = AnyCalendar::new(data.cal.into());

    let mut options = DateFromFieldsOptions::default();

    options.overflow = if data.overflow_constrain {
        Some(Overflow::Constrain)
    } else {
        Some(Overflow::Reject)
    };

    let mut fields = DateFields::default();
    fields.extended_year = Some(data.year);
    fields.day = NonZeroU8::new(data.day);
    let date = Date::try_from_fields(fields, options, calendar);
});
```

</details>

### PR DESCRIPTION
**Pull request by Manishearth**
Fixes #7049

I put some effort into making sure that type errors are returned before range errors, which makes it easier for Temporal to use this directly (otherwise it would have to hoist type errors out to be 100% spec compliant).

After discussion with @sffc, I decided not to have this check everywhere: only `from_fields` and `from_codes` have this check; calendar-specific constructors do not, and constructing from RataDie does not either. This is fine, it lets people stretch calendars to their limits if they really want.

### CODE REVIEW

File: components/calendar/src/cal/chinese.rs [hunk 1]
```diff
@@ -1671,6 +1672,25 @@ mod test {
...
+            day: NonZero::new(1),
+            ..Default::default()
+        };
+        let options = DateFromFieldsOptions {
+            overflow: Some(Overflow::Reject),
+            ..Default::default()
+        };
+
+        let cal = LunarChinese::new_china();
+        assert!(Date::try_from_fields(fields, options, cal).is_err());
```
Comment (sffc) [inline components/calendar/src/cal/chinese.rs]: Nit: Assert that it matches the correct error type, which should be Range as opposed to something else

File: components/calendar/src/cal/chinese.rs [hunk 2]
```diff
@@ -1671,6 +1672,25 @@ mod test {
         );
     }
 
+    #[test]
+    fn test_from_fields_regress_7049() {
```
Comment (sffc) [inline components/calendar/src/cal/chinese.rs:1677]: Nit: Add MonthDay and YearMonth tests, and missing Day tests

**Comment by Manishearth** [comment]
> IIUC this is an issue that is exclusive to the LunarChinese and Hijri calendars

No, it's not, the fuzzer found overflows in _every_ calendar. I only posted some of them in https://github.com/unicode-org/icu4x/issues/7049, but my fuzz test was finding issues for each one.

10e6 is not where our code starts producing overflows, it is the safe range we can make guarantees about, and it's the one we've exhaustively tested. I think it's not a bad look as long as we message it correctly.

**Comment by robertbastian** [comment]
> No, it's not, the fuzzer found overflows in every calendar. I only posted some of them in https://github.com/unicode-org/icu4x/issues/7049, but my fuzz test was finding issues for each one.

Can that not be fixed? I'm curious where this overflow happens, and whether a limit like `i32::MAX/2` would be more appropriate.

**Comment by Manishearth** [comment]
Here's a failing Buddhist value

```
	FuzzInput {
	    year: -2147483648,
	    month: 134,
	    day: 46,
	    month_interpretation: Ordinal,
	    overflow_constrain: false,
	    cal: Buddhist,
	}
```

It's 2^31, so yeah, that's probably fixable with a wider range. I guess we can have a per-calendar range check; FromFields can specify a min and max value.

Of course, if this is per-calendar, calendar conversion would mean that you can still take a valid ISO date and convert it into an "out of range" Chinese one.

> While this approach might solve problems in from_fields, it will still be possible to create Dates which violate invariants through those other APIs (and because we only fuzz from_fields, it hides these issues).

This was deliberate: the issue can be narrowly solved in from_fields but infallible calendar conversion means that it can't ever be truly eliminated from calendar code completely. I want to fix from_fields and have a narrower guarantee there, and in the future we can consider tweaking the guarantee on the other constructors.

**Comment by Manishearth** [comment]
From fuzzing it seems like Chinese is okay with year values bounded by `i32::MAX / 8`. So we could still have a cross-calendar bound there.

**Comment by Manishearth** [comment]
Nope, UAQ still errors on 197001411.

**Comment by robertbastian** [comment]
> Here's a failing Buddhist value

Yeah because Buddhist is an offset of Gregorian, so the addition/subtraction will overflow. As long as it's just additions (hope we don't mulitply years), MAX/2 should solve that. Such a limit we wouldn't even have to document, or at least not justify with "we don't know how to get rid of overflows other than this".


> Nope, UAQ still errors on 197001411.

That's an issue with the year data which I think I fixed in #7065?

**Comment by Manishearth** [comment]
I expanded the range to ±2²⁷, whcih is ±134_217_728. 28 might be possible after the UAQ fix.

**Comment by Manishearth** [comment]
Even with your patch I get the following panic if I reduce the 16 to an 8. So I think ±2²⁷ is the best we can do for now. We can always expand it later if we find ways of making it work.

```
thread '<unnamed>' (1420452) panicked at /home/manishearth/dev/icu4x/components/calendar/src/cal/hijri.rs:373:39:
attempt to multiply with overflow


	FuzzInput {
	    year: 238236467,
	    month: 51,
	    day: 51,
	    month_interpretation: CodeLeap,
	    overflow_constrain: true,
	    cal: HijriTabularTypeIIFriday,
	}
```

note that the used year value is `year % (i32::MAX / 8)`, which in this case is still `238236467`.

File: components/calendar/src/calendar_arithmetic.rs [hunk 3]
```diff
@@ -419,6 +423,18 @@ pub(crate) struct ArithmeticDateBuilder<YearInfo> {
...
 
+fn extended_year_as_year_info<YearInfo, C>(
+    extended_year: i32,
+    cal: &C,
+) -> Result<YearInfo, DateError>
+where
+    C: DateFieldsResolver<YearInfo = YearInfo>,
+{
+    // Check that the year is in range to avoid any arithmetic overflow.
+    range_check(extended_year, "year", -1_000_000..=1_000_000)?;
```
Comment (robertbastian) [inline components/calendar/src/calendar_arithmetic.rs]:
```suggestion
    range_check(extended_year, "year", VALID_YEAR_RANGE)?;
```

File: components/calendar/src/date.rs [hunk 4]
```diff
@@ -144,6 +148,11 @@ impl<A: AsCalendar> Date<A> {
     /// and the month as either ordinal or month code. It can constrain out-of-bounds values
     /// and fill in missing fields. See [`DateFromFieldsOptions`] for more information.
     ///
+    /// This function will not accept year/extended_year values that are outside of the range `[-2²⁷, 2²⁷]`,
+    /// regardless of the calendar, instead returning a [`DateError::Range`]. This is to protect clients
+    /// from bugs due to arithmetic overflow. Currently, calendar-specific `Date::try_new_calendarname()` constructors
```
Comment (robertbastian) [inline components/calendar/src/date.rs]: please remove the overflow justification.

```suggestion
    /// regardless of the calendar, instead returning a [`DateError::Range`]. Currently, calendar-specific `Date::try_new_calendarname()` constructors
```

File: components/calendar/src/calendar_arithmetic.rs [hunk 5]
```diff
@@ -448,53 +444,69 @@ where
...
+                    } else {
+                        return Err(DateError::NotEnoughFields);
+                    }
+                }
+            },
+        };
+
+        if fields.month_code.is_none() && fields.ordinal_month.is_none() {
+            // We're returning this error early so that we return structural type
+            // errors before range errors, see comment in Range.
```
Comment (robertbastian) [inline components/calendar/src/calendar_arithmetic.rs]: which comment is this referring to? I assume not the `Range` type

File: components/calendar/src/calendar_arithmetic.rs [hunk 6]
```diff
@@ -419,6 +423,18 @@ pub(crate) struct ArithmeticDateBuilder<YearInfo> {
     pub(crate) day: u8,
 }
 
+fn extended_year_as_year_info<YearInfo, C>(
```
Comment (robertbastian) [inline components/calendar/src/calendar_arithmetic.rs:648]: issue: if the range is a precondition for `year_info_from_extended` to not panic, then it should be checked in `year_info_from_extended`, not in this separate code path (that might be accidentally not used).

moving it to `year_info_from_extended` also allows us to have appropriate bounds per calendar. for example for many calendars, all years are valid. for `AbstractGregorian` `year_info_from_extended` is `extended_year + Y::EXTENDED_YEAR_OFFSET`, which can be changed to checked addition. Only a few calendars, actually need the bound you're hardcoding here.

File: components/calendar/src/date.rs (hunk 4 above)
Comment (Manishearth) [reply components/calendar/src/date.rs]: Why? I think it makes sense to give people an idea of what we are trying to prevent here (and it makes the order of magnitude of the choice of range relatively clear).

It means that overflow in these APIs is still considered a bug, whereas it won't necessarily be for the other ways of making Dates. Over time we can see if we wish to handle this there too, and docs can be updated accordingly.

File: components/calendar/src/calendar_arithmetic.rs (hunk 6 above)
Comment (Manishearth) [reply components/calendar/src/calendar_arithmetic.rs:648]: I deliberately don't want it to be per calendar just yet. We can choose to expand the range in the future, for now I want a simple, consistent check that serves our needs for 2.1. That includes having it be in one place.

It's also a precondition for the era-year code path and that's trickier to consistently check across calendars. The current state of this check is "any provided year value must be in this relatively generous range" which is a good starting point. If we want to make this per calendar, we can do some more per calendar testing, but I do not wish to block 2.1 on that.

I consider this to be a significant improvement over the status quo, and a stepping stone to a final state we do not yet have consensus on the precise nature of. In particular, the potential goals of having per calendar flexibility and not being able to "backdoor" this via calendar conversion are at odds, and most ways of resolving that conflict would be much more brittle than this. I do not think that is a discussion that must block the release, because I do not think there's anything here that's not changeable, though we may need to consider the impact on the Rules traits _if_ they graduate in this release (unlikely).


From a client perspective, I have been dealing with piles and piles of mostly worthless, noisy fuzzer bugs because ICU4X has debug panicky APIs. I think that's a sufficiently strong need to justify fixing this to this extent now (preventing problems in a major client with a simple policy), which can be made more robust in the future if we want.

Comment (robertbastian) [reply components/calendar/src/calendar_arithmetic.rs:648]: Can you leave some of this explanation as a comment in the code? In particular, that the global range can be replaced by per-calendar checks, and maybe link to an issue

File: components/calendar/src/date.rs (hunk 4 above)
Comment (robertbastian) [reply components/calendar/src/date.rs]: our code should be/have been written in a way that avoids overflows. if we'd had the range from the beginning, and then used it to justify the safety of our arithmetic, we wouldn't now justify the range with the overflowing of our arithmetic.

I also find it weird to say "protect clients from bugs due to arithmetic overflow". if there's an overflow, that's _our_ bug, not the client's bug. saying "protect clients from debug panics due to arithmetic overflows" would be more correct, but I still don't like that because I'd prefer to give the appearance that our code was written with overflows in mind in the first place

Comment (Manishearth) [reply components/calendar/src/date.rs]: Sure, it should have been written with overflows in mind in the first place, but that would still look something like this. There are only two possible solutions for overflows: either we have GIGO (usually saturation) behavior, or throw an error. We've picked the error one here. There are different ways for us to do the error thing, but it would still ultimately be "we do not accept all i32 year values".

I don't think "protect clients from bugs due to arithmetic overflow" makes it sound like it's the clients' bug. It protects client applications from having issues due to overflow.

Comment (Manishearth) [reply components/calendar/src/date.rs]: https://github.com/unicode-org/icu4x/issues/7076

**Comment by Manishearth** [comment]
(force push was a rebase, only the last commit "review comments" is new)

**Comment by Manishearth** [comment]
I have a slight preference for the range-change to be a third PR but we can figure that out separately. Fine to include in that PR for now, I won't be sure until I get a better look at it.

File: components/calendar/src/calendar_arithmetic.rs [hunk 7]
```diff
@@ -711,6 +752,7 @@ where
                 }
                 None => match ordinal_month_as_u8 {
                     Some(month) => month,
+                    // This is technically unreachable since it's checked early above
```
Comment (sffc) [inline components/calendar/src/calendar_arithmetic.rs:755]: Nit: Then debug assert that it is unreachable, please.

(this is feedback I gave orally but didn't write down in a GitHub comment)

File: components/calendar/src/calendar_arithmetic.rs [hunk 8]
```diff
@@ -654,49 +675,69 @@ where
         C: DateFieldsResolver<YearInfo = YearInfo>,
     {
         let missing_fields_strategy = options.missing_fields_strategy.unwrap_or_default();
-        let maybe_year = {
-            let extended_year_as_year_info = fields
-                .extended_year
-                .map(|extended_year| cal.year_info_from_extended(extended_year));
+
```
Comment (sffc) [inline components/calendar/src/calendar_arithmetic.rs:678]: Process Discussion:

This is code that I "care a lot about" because it is code that I wrote a matter of weeks ago, and it is being changed in major ways. My "care a lot about it" would decay over time, but this is still very new code that I spent a lot of time thinking about. Manish reviewed this code so I would expect that he would have been able to correctly identify that status.

I left a comment on an older version of this PR. However, after I left that comment, this function changed in a large way, so it "looks like" I was OK with the PR, even though I hadn't seen these additional changes.

The correct process would have been:

1. Shane leaves comment on v1 of the PR
2. Manish updates the PR
3. Manish re-requests Shane's review (this is the step that doesn't appear to have happened)
4. Shane leaves a re-review, which he can see in his GitHub open review requests queue which he endeavors to clear out every 24 hours (this didn't happen because it wasn't in my open review requests), and if Shane doesn't reply within a reasonable statute of limitations, then the PR could be merged despite his lack of response. This sat for 1 business day without a response, which doesn't exceed the statute of limitations.

The fail-safe would be for Manish or Robert to flag this function as one Shane cares about, notice that Shane didn't see the latest changes, and ask for explicit LGTM. It seems the fail-safe also didn't happen.

File: components/calendar/src/cal/chinese.rs (hunk 2 above)
Comment (sffc) [reply components/calendar/src/cal/chinese.rs:1677]: This doesn't appear to have gotten done. https://github.com/unicode-org/icu4x/issues/7083

Comment (Manishearth) [reply components/calendar/src/cal/chinese.rs:1677]: Yep, sorry, I have a local branch for this that I didn't finish up and push. I'll do that tomorrow.

File: components/calendar/src/calendar_arithmetic.rs (hunk 7 above)
Comment (Manishearth) [reply components/calendar/src/calendar_arithmetic.rs:755]: As I said then I really want to be careful about debug assertions in this code, but I think this case is fine.

Comment (Manishearth) [reply components/calendar/src/calendar_arithmetic.rs:755]: https://github.com/unicode-org/icu4x/pull/7087

File: components/calendar/src/calendar_arithmetic.rs (hunk 8 above)
Comment (Manishearth) [reply components/calendar/src/calendar_arithmetic.rs:678]: > Manish reviewed this code so I would expect that he would have been able to correctly identify that status.

In that case I don't think I have a good mental model about the type of code you would care about if you care about this, after our discussions about this PR.

It's generally hard to know in advance if some code is something an author has spent a lot of time thinking about unless it that thinking happened through the review process.

We explicitly had an in-person discussion about the strategy to use here, and I even wrote some of this code in front of you, checking with you on some of the stages. The code here did not change that much since that discussion, with the main change being to comments. My expectation was that we were mostly aligned on the general shape of this code and it was Robert whom I would need to get some consensus with, which is what I pursued.  I think https://github.com/unicode-org/icu4x/pull/7062/commits/c0283f3eb0a2660c174f94870a19af222c8d5194 is the only actual change, the bulk of the work here was discussion with Robert. https://github.com/unicode-org/icu4x/pull/7062/commits/1c67bd3e75c8072166c0f111d87efcae8915e05a was a refactor I did in front of you.

I think it is unreasonable to expect me to know you would want to be a blocking reviewer on this. I expected you'd want to look at it eventually, but not as a blocking review.

(In this specific case, I merged once I had Robert's review because he's also working on improving the range check situation, by merging it I enabled a lot of progress on his PR #7065 during the time we were both online)

> this didn't happen because it wasn't in my open review requests

I guess when you leave a partial review it dismisses the request? Perhaps for partial reviews you should re-request review of yourself if you use that UI. This is just like re-marking an inbox item as unread/un-"done" after partially-but-not-completely consuming it. I can't know just from looking at it whether a review is a partial review or a full one.

My norm is to only re-request review of reviewers whose comments I'm addressing, unless I'm pushing a large enough change that I think I need to re-request review from others. The changes I made since your review were _extremely_ minor, mostly comments.

Personally I don't use "open review requests" for this since I use notification filters. So I don't know the details of what does and doesn't work.

A slight mistake I made here was starting the work for https://github.com/unicode-org/icu4x/pull/7062#discussion_r2418252951 as a separate thing and then not leaving a comment saying I was planning on doing that, or waiting for a response here. That was my bad: I thought I had left a comment there or or maybe said something in person and it just hadn't happened.
