### PR TITLE
fix(normalizer): Add missing backticks to doc comment

### LINKED ISSUE #7632: Fix clippy::doc-markdown documentation warning in icu_normalizer
The code in `icu_normalizer/src/lib.rs` has documentation warnings from clippy about missing backticks around `icu_properties` and `CanonicalCombiningClass`. This change adds the missing backticks to satisfy the `clippy::doc-markdown` lint.

### PR DESCRIPTION
**Pull request by mega123-art**
Fixes #7632. This PR suppresses `clippy::doc-markdown` warnings in `components/normalizer/src/lib.rs` by wrapping `icu_properties` and `CanonicalCombiningClass` in backticks.

### CODE REVIEW

File: components/normalizer/src/lib.rs [hunk 1]
```diff
@@ -170,7 +170,7 @@ fn likely(b: bool) -> bool {
     b
 }
 
-/// This type exists as a shim for icu_properties CanonicalCombiningClass when the crate is disabled
+/// This type exists as a shim for `icu_properties` `CanonicalCombiningClass` when the crate is disabled
 /// It should not be exposed to users.
```
Comment (robertbastian) [inline components/normalizer/src/lib.rs]: this should not actually be a doc comment if "It should not be exposed to users".

```suggestion
// This type exists as a shim for `icu_properties` `CanonicalCombiningClass` when the crate is disabled
// It should not be exposed to users.
```

**Comment by mega123-art** [comment]
@robertbastian sir are we good to merge this pr now?
