### PR TITLE
Fix maximize function

### LINKED ISSUE #817: Incorrect likely subtags maximization of und-Latn-AQ
This testcase in Firefox [1] maximizes `und-AQ` twice. The first call results in `und-latn-AQ` but the second call results in `en-latn-AQ`. Calling maximize() twice should not change the result (otherwise it would not be maximized!), so there must be a bug in our handling of maximizing `und` languages.

To work on this bug:
* Code is found in https://github.com/unicode-org/icu4x/blob/b56441cc06ca09210d7859e7628f06ac7bb7336c/components/locale_canonicalizer/src/locale_canonicalizer.rs#L458
* Unit tests are present here: https://github.com/unicode-org/icu4x/blob/main/components/locale_canonicalizer/tests/fixtures/maximize.json
* The algorithm is defined here: https://www.unicode.org/reports/tr35/#Likely_Subtags

[1] https://searchfox.org/mozilla-central/rev/c114db74a92cf15096dfda02255e125949b0e070/js/src/tests/non262/Intl/Locale/likely-subtags.js#5

### PR DESCRIPTION
**Pull request by pandusonu2**
Fixes #817

### CODE REVIEW

**Review by Manishearth — DISMISSED** [review]
code looks okay to me but I'd like @dminor to be the one to give it final approval

**Comment by pandusonu2** [comment]
@dminor PR bump

File: components/locale_canonicalizer/src/locale_canonicalizer.rs [hunk 1]
```diff
@@ -186,11 +186,23 @@ fn update_langid(
     entry: &LanguageIdentifier,
     langid: &mut LanguageIdentifier,
 ) -> CanonicalizationResult {
+    let language_unmodified = langid.language.clone();
+    let script_unmodified = langid.script.clone();
+    let region_unmodified = langid.region.clone();
```
Comment (zbraniecki) [inline components/locale_canonicalizer/src/locale_canonicalizer.rs:191]: `question`: wouldn't it be much cheaper to register changes, rather than clone and compare?

I mean:

```rust
let language_modified = false;

if (...) {
    language_modified = true;
}

if !language_modified {
    return CanonicalizationResult::Unmodified;
}
```
?

File: components/locale_canonicalizer/src/locale_canonicalizer.rs [hunk 2]
```diff
@@ -533,12 +541,14 @@ impl<'data> LocaleCanonicalizer<'data> {
                 maximize_locale!(langid, data.language_script, language, script.into());
             }
             maximize_locale!(langid, data.language, language);
-        } else if let Some(script) = langid.script {
+        }
+        if let Some(script) = langid.script {
```
[the remark this answers is not in the document]
Comment (dminor) [reply components/locale_canonicalizer/src/locale_canonicalizer.rs:549]: You're right, it's hidden in the macro, sorry that I missed that.

**Review by dminor — DISMISSED** [review]
Sorry about the very long delay in reviewing this. This looks fine to me, but please have a look at Zibi's comments as well.

**Comment by sffc** [comment]
@pandusonu2 PTAL at Zibi's question above as well as the failing Clippy lint

File: components/locale_canonicalizer/src/locale_canonicalizer.rs (hunk 1 above)
Comment (pandusonu2) [reply components/locale_canonicalizer/src/locale_canonicalizer.rs]: Done, please check the PR now

**Review by dminor — DISMISSED** [review]

File: components/locale_canonicalizer/src/locale_canonicalizer.rs [hunk 3]
```diff
@@ -186,12 +186,28 @@ fn update_langid(
     entry: &LanguageIdentifier,
     langid: &mut LanguageIdentifier,
 ) -> CanonicalizationResult {
-    if langid.language.is_empty() {
+    let mut modified: bool = false;
```
Comment (zbraniecki) [inline components/locale_canonicalizer/src/locale_canonicalizer.rs:189]: `nit (n-b)`: you don't need to specify the type, its derived from the initial value.

File: components/locale_canonicalizer/src/locale_canonicalizer.rs [hunk 4]
```diff
@@ -186,12 +186,28 @@ fn update_langid(
...
+    if langid.region.is_none() && entry.region.is_some() {
+        langid.region = entry.region;
+        modified = true;
+    }
+
+    if modified {
+        return CanonicalizationResult::Modified;
+    }
+
+    CanonicalizationResult::Unmodified
```
Comment (zbraniecki) [inline components/locale_canonicalizer/src/locale_canonicalizer.rs:210]: `nit (n-b)`: I'm surprised `cargo clippy` didn't warn you, Rust prefers matching branches and implicit `return`:

```rust
if modified {
    CanonicalizationResult::Modified
} else {
    CanonicalizationResult::Unmodified
}
```

**Review by zbraniecki — DISMISSED** [review]
lgtm! Minor stylistic nits left.

**Review by zbraniecki — APPROVED** [review]
lgtm!

**Comment by pandusonu2** [comment]
@sffc  I dont have permissions to merge it. Please do merge it, after the tests are run
