### PR TITLE
Correct error types for `icu_provider_fs`

### LINKED ISSUE #3610: No provider should fail with MissingDataKey if it was built with a key but that key has no locales
Spawned out of https://github.com/unicode-org/icu4x/issues/3575

If a data provider is built with a key but the key has no data, it should not error with MissingDataKey, it should error with MissingLocale.

`BlobDataProvider` fixed this in https://github.com/unicode-org/icu4x/pull/3551. The adapters should just work with this (worth quickly checking if forking by key works correctly)

`FsDataProvider` needs to be fixed. Probably with a manifest change or some dummy file.

### PR DESCRIPTION
**Pull request by robertbastian**
Blocked on #3680 

Fixes #3610

### CODE REVIEW

**Review by Manishearth — DISMISSED** [review]
CI is sad

**Comment by robertbastian** [comment]
Yes this requires 1.64

**Review by Manishearth — APPROVED** [review]

File: provider/fs/src/export/fs_exporter.rs [hunk 1]
```diff
@@ -119,15 +119,19 @@ impl DataExporter for FilesystemExporter {
...
-        path_buf.set_extension(self.manifest.file_extension);
-
-        if let Some(parent_dir) = path_buf.parent() {
-            fs::create_dir_all(parent_dir)
-                .map_err(|e| DataError::from(e).with_path_context(&parent_dir))?;
-        }
+        let mut path_buf = self.root.clone().into_os_string();
+        write!(
+            &mut path_buf,
+            "/{key}/{locale}.{}",
```
Comment (sffc) [inline provider/fs/src/export/fs_exporter.rs:125]: Issue, here and elsewhere: using `/` is not good because Windows and other OSes need different separators. That is what PathBuf::push handles for us. I don't think either `write!` or `Path::new` fixes it for us since `write!` is writing directly to a string and `Path::new` tries to borrow where possible.

File: provider/fs/src/export/fs_exporter.rs [hunk 2]
```diff
@@ -163,6 +167,16 @@ impl DataExporter for FilesystemExporter {
         Ok(())
     }
 
+    fn flush_with_fallback(&self, key: DataKey, _: FallbackMode) -> Result<(), DataError> {
+        let mut path_buf = self.root.clone().into_os_string();
+        write!(&mut path_buf, "/{key}").expect("infallible");
+
+        fs::create_dir_all(&path_buf)
+            .map_err(|e| DataError::from(e).with_path_context(&path_buf))?;
```
Comment (sffc) [inline provider/fs/src/export/fs_exporter.rs:175]: Suggestion: it might be useful to add a file like `.gitkeep` to the directory to prevent VCS systems from removing the empty directory.

File: provider/fs/src/export/fs_exporter.rs (hunk 1 above)
Comment (robertbastian) [reply provider/fs/src/export/fs_exporter.rs:125]: Apparently this works because Windows tests are not failing. Note that before we used `push(&str)`, which used `AsRef<Path> for &str`, so the slashes in the `str` were still forward slashes (and `push` itself doesn't replace them).

Comment (sffc) [reply provider/fs/src/export/fs_exporter.rs:125]: Okay, so before we were appending individual path segments for root, key, and locale, but the key can contain a slash which wasn't being processed.

I wouldn't be surprised if Windows accepts these characters but does some weird handling with them.

@eggrobin and @makotokato are the two ICU4X engineers who routinely use Windows and might be able to provide some insight here.
