### PR TITLE
Audit exhaustiveness of icu_calendar::types

### LINKED ISSUE #5797: Check exhaustiveness of `icu::calendar::types` types
Also the doc comment on `DayOfYearInfo` is broken.

### PR DESCRIPTION
**Pull request by Manishearth**
Fixes #5797

Currently in this scheme, MonthInfo and EraYear are not constructible by external users. I think that's okay for now, nad we can revisit if someone wishes to make custom calendars and needs these.

### CODE REVIEW

File: components/calendar/src/types.rs [hunk 1]
```diff
@@ -180,7 +180,7 @@ impl FormattingEra {
 }
 
 /// Year information for a year that is specified with an era
-#[derive(Copy, Clone, Debug, PartialEq)]
+#[derive(Copy, Clone, Debug, PartialEq, Default)]
```
Comment (sffc) [inline components/calendar/src/types.rs:183]: Why did you impl Default? There's not really a default year.

Comment (Manishearth) [reply components/calendar/src/types.rs:183]: Makes it convenient to construct. Generally I feel like non-exhaustive types should be constructible. We're not rigidly following that guideline here, but I'm trying to follow it where possible.

I don't mind removing this for now.

Comment (sffc) [reply components/calendar/src/types.rs:183]: Yeah we might consider adding a constructor, but I think avoid the scope creep for now.

**Comment by Manishearth** [comment]
autosubmit=on

File: components/calendar/src/types.rs [hunk 2]
```diff
@@ -355,9 +355,9 @@ impl MonthInfo {
         self.standard_code.parsed().map(|(_, l)| l).unwrap_or(false)
     }
 }
+
 /// A struct containing various details about the position of the day within a year. It is returned
-// by the [`day_of_year_info()`](trait.DateInput.html#tymethod.day_of_year_info) method of the
-// [`DateInput`] trait.
+/// by the `day_of_year_info()` method of the `DateInput` trait.
```
Comment (sffc) [inline components/calendar/src/types.rs:360]:
```suggestion
/// by [`Calendar::day_of_year_info()`].
```

File: components/calendar/src/types.rs [hunk 3]
```diff
@@ -355,9 +355,9 @@ impl MonthInfo {
...
 #[derive(Copy, Clone, Debug, PartialEq)]
 #[allow(clippy::exhaustive_structs)] // this type is stable
```
Comment (sffc) [inline components/calendar/src/types.rs:362]: Why did you keep this one exhaustive?

**Review by sffc — APPROVED** [review]

File: components/calendar/src/types.rs (hunk 3 above)
Comment (Manishearth) [reply components/calendar/src/types.rs:362]: Hm, I thought I had fixed this already. Perhaps in the reshuffle of ctors it got undone

**Review by sffc — APPROVED** [review]
