### PR TITLE
Fix datagen to propagate extension keywords and aux keys to child locales

### LINKED ISSUE #4488: Auxiliary keys don't work with hybrid or preresolved fallback
The way datagen works with hybrid and preresolved fallback is it adds the explicitly requested locales to the list of locales to export. However, it needs to also add the aux keys to those locales, which it is not doing. This means that if you run datagen with `en-US` as a requested locale, you get `en-x-3` but not `en-US-x-3` since there is no `en-US` JSON file.

Would like #4319 to land first.

### PR DESCRIPTION
**Pull request by sffc**
Fixes #4488

If `ar-SA` is requested and `ar-u-nu-latn` exists, `ar-SA-u-nu-latn` should be included, even if that locale isn't in CLDR data by itself.

This shows up also in the experimental skeleton keys. CC @blaynem

It also impacts neo datetime because of aux keys.

### CODE REVIEW

File: provider/datagen/src/driver.rs [hunk 1]
```diff
@@ -468,97 +468,160 @@ impl DatagenDriver {
...
 
+struct ExplicitImplicitLocaleSets {
+    explicit: HashSet<DataLocale>,
+    implicit: HashSet<DataLocale>,
+}
+
+/// Resolves the set of explicit langids and the supported locales into two sets of locales:
+///
+/// - `explicit` contains the explicit langids but with aux keys and extension keywords included
+/// - `implcit` contains any locale reachable by fallback from an `explicit` locale
```
Comment (Manishearth) [inline provider/datagen/src/driver.rs:479]: nit: I'd like more comments here to explain what this handles, with examples referencing the locales mentioned in comments below

**Review by Manishearth — COMMENTED** [review]
Overall looks good but I want to defer to @robertbastian on final review

File: provider/datagen/src/driver.rs (hunk 1 above)
Comment (sffc) [reply provider/datagen/src/driver.rs]: Added more docs

**Review by robertbastian — APPROVED** [review]
