### PR TITLE
Use `icu::calendar` as the source of truth for era indices

### LINKED ISSUE #6444: Formatting era index is really bad and will break in CLDR 48
We should try to avoid shipping ICU4X code that we know will break in the next CLDR release.

CLDR will be changing the AH era to be index 1 instead of index 0 in the next release:

https://github.com/unicode-org/cldr/pull/4581

This means that mismatched code and data will result in differing results, results that will be _outright wrong_. Not just unintelligible, but wrong. I noticed this in #6443

To fix this, I suggest making era index 0 be the primary era (all calendars using era indexes have a primary era) and index 1 the secondary era.

Except that might not work in Ethiopian... maybe just special-case Ethiopian?

@robertbastian @Manishearth

### PR DESCRIPTION
**Pull request by robertbastian**
Based on #6451 

Fixes #6444

### CODE REVIEW

**Review by sffc — COMMENTED** [review]
Seems about right; shouldn't there be a diff? Or not because you didn't actually change the indices yet

**Comment by robertbastian** [comment]
This doesn't change the indices, but it gets the values from `icu::calendar` instead of CLDR. They currently match, hence no diff.

File: components/calendar/src/types.rs [hunk 1]
```diff
@@ -92,11 +92,7 @@ pub struct EraYear {
     pub era: TinyStr16,
     /// An era index, for calendars with a small set of eras.
     ///
-    /// It is obtained by ordering all eras' start/end dates, and for eras sharing a date, put the negative
-    /// one first. For example, bce < ce.
-    ///
-    /// As eras might be added or removed across CLDR releases, this does not have a stable correspondence
-    /// with the era code.
+    /// The only guarantee we make is that these values are stable, even under CLDR code changes.
     pub era_index: Option<u8>,
```
Comment (sffc) [inline components/calendar/src/types.rs:96]: Nit (Optional): Don't change these docs until you actually change the numbers. I read this and thought this PR was changing the indices to conform to our new requirement, but it is just a refactoring to change the source of truth.

**Review by sffc — APPROVED** [review]

**Comment by sffc** [comment]
I edited the PR title.

File: components/calendar/src/types.rs (hunk 1 above)
Comment (robertbastian) [reply components/calendar/src/types.rs:96]: well it's amibguous what "all eras' start/end dates" means across CLDR releases, so I don't think the current docs are accurate

**Comment by Manishearth** [comment]
This is a clever solution
