### PR TITLE
Fix reexport documentation to be clearer when things are reexports

### LINKED ISSUE #6240: Rustdoc doesn't indicate re-exports for input types?
For example,

https://unicode-org.github.io/icu4x/rustdoc/icu/datetime/input/index.html

None of the types suggest that they are re-exports. Did this break very recently? @Manishearth

### PR DESCRIPTION
**Pull request by Manishearth**
Also moves public/stable types TimeZone and TimeZoneVariant out of the provider module, turning the reexport into the other direction. Even with `doc(no_inline)`, I'm more comfortable with the provider module only containing unstable types and reexports of stable types.

Fixes #6240

### CODE REVIEW

File: components/calendar/src/date.rs [hunk 1]
```diff
@@ -89,6 +89,8 @@ impl<C> Deref for Ref<'_, C> {
 
 /// A date for a given calendar.
 ///
+/// **This type originates from the [`icu_calendar`](docs.rs/icu_calendar) crate, though it may be found reexported elsewhere.**
```
Comment (sffc) [inline components/calendar/src/date.rs:92]: Suggestion, here and elsewhere:

```suggestion
/// **The primary definition of this type is in the [`icu_calendar`](docs.rs/icu_calendar) crate.
/// Other ICU4X crates re-export it for convenience.**
```

File: components/datetime/src/lib.rs [hunk 2]
```diff
@@ -137,26 +137,14 @@ pub mod preferences {
 }
 
 /// Types that can be fed to [`DateTimeFormatter`]/[`FixedCalendarDateTimeFormatter`].
+///
+/// This module contains reexports from the [`icu_calendar`] and [`icu_time`] crates.
```
Comment (sffc) [inline components/datetime/src/lib.rs:141]: Nit, here and elsewhere:

```suggestion
/// This module contains re-exports from the [`icu_calendar`] and [`icu_time`] crates.
```

**Review by sffc — COMMENTED** [review]
Thanks! I'm being picky with language, but the primary purpose of this PR is improving language.

**Review by sffc — APPROVED** [review]

File: components/time/src/zone/mod.rs [hunk 3]
```diff
@@ -158,7 +162,120 @@ pub mod models {
...
+/// );
+/// assert_eq!(
+///     parser.parse("Europe/London"),
+///     TimeZone(tinystr!(8, "gblon"))
+/// );
+/// ```
+#[repr(transparent)]
+#[derive(Debug, Clone, Copy, Eq, Ord, PartialEq, PartialOrd, yoke::Yokeable, ULE, Hash)]
+#[cfg_attr(feature = "datagen", derive(serde::Serialize, databake::Bake))]
+#[cfg_attr(feature = "datagen", databake(path = icu_time))]
```
Comment (robertbastian) [inline components/time/src/zone/mod.rs:199]: nit: should be `icu_time::zone` as the canonical location

File: components/calendar/src/date.rs [hunk 4]
```diff
@@ -89,6 +89,8 @@ impl<C> Deref for Ref<'_, C> {
 
 /// A date for a given calendar.
 ///
+/// **The primary definition of this type is in the [`icu_calendar`](docs.rs/icu_calendar) crate. Other ICU4X crates re-export it for convenience.**
```
Comment (robertbastian) [inline components/calendar/src/date.rs:92]: you need to write https://docs.rs for a working link
