### PR TITLE
ixdtf: Correctly handle ambiguous annotations

### LINKED ISSUE #6775: ixdtf should parse timezone annotation "[cet]" as a timezone
Currently, parsing zoned datetime strings like `2020-01-01[cet]` will fail in `parse_ambiguous_tz_annotation` at https://github.com/unicode-org/icu4x/blob/d4eb34d9a0f6f09dae603a397e13a102b3cb5510/utils/ixdtf/src/parsers/timezone.rs#L62, since the `c` in `cet` matches [AKeyLeadingChar](https://tc39.es/proposal-temporal/#prod-AKeyLeadingChar).

I guess this function is attempting to deal with `[u-ca=foo]` and other annotations. I think instead of returning  an error on `is_annotation_close` we should be attempting to parse it as a timezone.

cc @nekevss

### PR DESCRIPTION
**Pull request by Manishearth**
fixes #6775

### CODE REVIEW

File: utils/ixdtf/src/parsers/timezone.rs [hunk 1]
```diff
@@ -52,14 +59,19 @@ pub(crate) fn parse_ambiguous_tz_annotation<'a, T: EncodingType>(
...
             while let Some(ch) = cursor.peek_n(peek_pos)? {
                 if is_tz_name_separator(ch) || (is_tz_char(ch) && !is_a_key_char(ch)) {
+                    // This is stuff like `asia/kolkata` where there is a non-annotation
+                    // character (the slash).
                     let tz = parse_tz_annotation(cursor)?;
                     return Ok(Some(tz));
                 } else if is_annotation_key_value_separator(ch)
                     || (is_a_key_char(ch) && !is_tz_char(ch))
                 {
+                    // We have an `=` sigh, this is a non-tz annotation
```
Comment (robertbastian) [inline utils/ixdtf/src/parsers/timezone.rs]:
```suggestion
                    // We have an `=` sign, this is a non-tz annotation
```

File: utils/ixdtf/src/parsers/tests.rs [hunk 2]
```diff
@@ -586,6 +586,31 @@ fn valid_unambiguous_time() {
     }
 }
 
+#[test]
+fn ambiguous_annotations() {
+    const TESTS_TIMEZONE: &[&str] = &[
+        "2020-01-01[Asia/Kolkata]",
+        // Has a slash
```
Comment (robertbastian) [inline utils/ixdtf/src/parsers/tests.rs:586]: they both have a slash though

**Review by robertbastian — COMMENTED** [review]
`Invalid annotation parsing: "2021-01-29 02:12:48+01:00:00[u][u-ca=iso8601]" should fail to parse.`

File: utils/ixdtf/src/parsers/tests.rs (hunk 2 above)
Comment (Manishearth) [reply utils/ixdtf/src/parsers/tests.rs:586]: oops, first should say "starts with capital letter"

**Comment by Manishearth** [comment]
> Invalid annotation parsing: "2021-01-29 02:12:48+01:00:00[u][u-ca=iso8601]" should fail to parse.

Hmm, the temporal spec, where this annotation syntax comes from, allows multiple annotations after a single optional TimeZoneAnnotation. Unclear to me that this is actually invalid.

**Comment by nekevss** [comment]
Huh, actually looking at that test now. I think it may be a bad test.

This could probably just scan forward for a key-value separator `=`. If found, it parses as a key-value annotation, and if not found, it parses as a time zone annotation.

**Comment by Manishearth** [comment]
That's a good point, given that this only has two return types that matter now.

**Review by robertbastian — APPROVED** [review]
