### PR TITLE
Uniset cleanup

### LINKED ISSUE #944: Clean up uniset code
While working on the enumerated properties data provider, I've amassed a collection of small changes to the uniset code. Some of them merit further discussion. (I've already opened #940 to track using ResourceOptions for enum values instead of baking it into the key.) In no particular order:

1. As mentioned above, I think we should consider using ResourceOptions for enum values.
2. I think we should extend enum_props::GeneralCategory to include group properties (like Letter, which is a union of five subcategories). I expect that the higher-level categories like Letter and Number are going to be at least as useful, if not more useful, than the more specific versions. I don't see any value in exposing the internal data model to the user, particularly since CasedLetter would require a third tier in the hierarchy all to itself. Regarding the alignment of enum values between ICU4C and ICU4X, ICU4C already requires the user to pass in U_GET_GC_MASK(category) instead of the UCharCategory itself, precisely so that it can support higher-level categories. 
3. The list of scripts in enum_props::Script includes some scripts that don't have any associated entries in the PPUCD (like Cirth, Tolkien's runic alphabet, which is included in ISO 15924 but not in Unicode. Conversely, some scripts that exist in the PPUCD data exported from ICU4C aren't represented in the enum. 
4. We don't have a great story yet for making iterators available through FFI. Adding UnicodeSet::getRange makes it much less cumbersome to write a decent C++ FFI for irregexp. We can always deprecate it in the future if we come up with something better.
5. If we break the D: DataProvider<'data, ...> boilerplate in all the props.rs function signatures into a where clause, everything is much more readable, and it no longer seems necessary to have a rustfmt exemption. (Also there are some stale clippy exceptions that can be deleted without clippy complaining.)
6. We already support surrogate codepoints in UnicodeSet by virtue of UnicodeSetBuilder::add_u32. The data provider needs something like UnicodeSetBuilder::add_range_u32 to be able to support `General_Category=Surrogate`, because the endpoints of the range can't be represented as Rust `char`s. We can also add, for example, UnicodeSet::contains_range_u32; on the other hand, if the main use case for that would be checking for the presence of surrogates, maybe we should have something more direct.

### PR DESCRIPTION
**Pull request by iainireland**
Fixes #944. This covers all the topics I listed except point 1, which we decided not to do (see #940).

### CODE REVIEW

File: components/uniset/src/uniset.rs [hunk 1]
```diff
@@ -168,14 +179,26 @@ impl UnicodeSet {
...
     }
 
     /// Returns the number of ranges contained in this [`UnicodeSet`]
     pub fn get_range_count(&self) -> usize {
         self.inv_list.len() / 2
     }
 
+    /// Returns a specific range contained in this [`UnicodeSet`] by index.
+    /// Intended for use in FFI.
+    pub fn get_range(&self, idx: usize) -> Option<RangeInclusive<u32>> {
```
Comment (sffc) [inline components/uniset/src/uniset.rs:194]: Suggestion:

```suggestion
    pub fn get_nth_range(&self, idx: usize) -> Option<RangeInclusive<u32>> {
```

Or perhaps:

- `get_range_at`
- `get_range_at_index`
- `range_at_index`

File: provider/uprops/src/error.rs [hunk 2]
```diff
@@ -12,8 +12,6 @@ pub enum Error {
     Io(std::io::Error, PathBuf),
     #[displaydoc("{0}: {1:?}")]
     Toml(toml::de::Error, PathBuf),
-    #[displaydoc("Invalid range: {0}-{1}")]
-    InvalidCharRange(u32, u32),
```
Comment (sffc) [inline provider/uprops/src/error.rs:16]: Praise: Thanks for noticing that we can get error of this error variant!

File: components/uniset/src/enum_props.rs [hunk 3]
```diff
@@ -15,50 +13,85 @@ pub enum EnumeratedProperty {
...
 
 //// Enumerated property Script.
 ///
 /// For more information, see UAX #24: http://www.unicode.org/reports/tr24/.
 /// See UScriptCode in ICU4C.
+///
+/// This enum only contains variants for scripts that are used in the Unicode
+/// Property Database.
 #[derive(Clone, PartialEq, Debug)]
 pub enum Script {
```
[the remark this answers is not in the document]
Comment (iainireland) [reply components/uniset/src/enum_props.rs:93]: In the context of uniset, we already fail relatively gracefully if the UCD changes. You can't request the set of characters in a newly-added script until we add support, but the datagen should work out fine if somebody downloads a newer version of the UCD. I can imagine that it might be more of an issue for the code point trie, but I think it's best to address that as part of the code point trie work where we have better perspective.

We should probably add `#[non_exhaustive]` here, though. (And maybe also GeneralCategory? I thought I had read somewhere that ICU had committed to not adding new general categories, but I can't find any evidence.)

**Review by sffc — APPROVED** [review]

**Comment by sffc** [comment]
@echeran is OOO until 2021-08-25 so you could consider merging this now and doing a potential follow-up PR in a few weeks once @echeran has had the opportunity to review.
