### PR TITLE
Removing `dhat` dependency from `icu_provider`

### LINKED ISSUE #2953: Fix binsize CI
The binsize CI is consistently getting stuck:

```
...
Writing wasmpkg/wat/yoke_derive.wat 
Writing wasmpkg/wat/zf_derive.wat 
Writing wasmpkg/wat/zv_serde.wat 
[cargo-make] INFO - Running Task: wasm-dcmp
Writing wasmpkg/wasm-decompile/and_list.dcmp 
Writing wasmpkg/wasm-decompile/borrowed_pattern.dcmp 
Writing wasmpkg/wasm-decompile/code_line_diff.dcmp 
Writing wasmpkg/wasm-decompile/derives.dcmp 
Writing wasmpkg/wasm-decompile/elevator_floors.dcmp 
Writing wasmpkg/wasm-decompile/filter_langids.dcmp 
Writing wasmpkg/wasm-decompile/iso_date_manipulations.dcmp 
Writing wasmpkg/wasm-decompile/iso_datetime_manipulations.dcmp 
Writing wasmpkg/wasm-decompile/language_names_hash_map.dcmp 
Writing wasmpkg/wasm-decompile/language_names_lite_map.dcmp 
Writing wasmpkg/wasm-decompile/litemap_bincode.dcmp 
Writing wasmpkg/wasm-decompile/litemap_postcard.dcmp 
Writing wasmpkg/wasm-decompile/make.dcmp 
Writing wasmpkg/wasm-decompile/make_var.dcmp 
Error: The operation was canceled.
```

### PR DESCRIPTION
**Pull request by robertbastian**
While it's an optional dependency, it is a runtime dependency, so global feature resolution might activate it.

### CODE REVIEW

File: provider/core/src/datagen/mod.rs [hunk 1]
```diff
@@ -108,11 +106,14 @@ macro_rules! make_exportable_provider {
                 match key.hashed() {
                     $(
                         $struct_m => {
-                            let heap_stats = from.attempt_zero_copy_heap_size::<$struct_m>();
-                            return Ok($crate::DataPayload::from_owned(heap_stats));
+                            let _reified_data: $crate::DataPayload<$struct_m> = buf
+                                .into_deserialized($crate::buf::BufferFormat::Postcard1)
+                                .expect("Failed to deserialize BufferMarker as postcard-1.0");
+                            use $crate::dynutil::UpcastDataPayload;
+                            Ok($crate::AnyMarker::upcast(_reified_data))
```
Comment (robertbastian) [inline provider/core/src/datagen/mod.rs:113]: We only need the side effect of this, but I thought we might as well return it as `Any`

Comment (robertbastian) [reply provider/core/src/datagen/mod.rs:113]: Ah this doesn't work because the upcast allocates

**Review by sffc — COMMENTED** [review]
(waiting to review until it passes CI)

File: provider/datagen/src/registry.rs [hunk 2]
```diff
@@ -81,6 +81,23 @@ macro_rules! registry {
             )+
             unreachable!("unregistered marker")
         }
+
+        #[doc(hidden)]
+        pub fn deserialize_and_discard<R>(key: DataKey, buf: DataPayload<BufferMarker>, r: impl Fn() -> R) -> Result<R, DataError> {
```
Comment (Manishearth) [inline provider/datagen/src/registry.rs:86]: question: is there a reason we need the callback? It's just called after deserialization, no? We'll know deserilization was successful from the error value of this function anyway

**Review by Manishearth — DISMISSED** [review]
minor issue about needing the callback

File: provider/datagen/src/registry.rs (hunk 2 above)
Comment (robertbastian) [reply provider/datagen/src/registry.rs:86]: There's a comment at the call site. We need to get the heap stats before the function returns, because otherwise the struct is dropped and we cannot distinguish between net violations and total violations.

**Review by sffc — APPROVED** [review]

**Review by Manishearth — APPROVED** [review]
