### PR TITLE
fix(datetime): Return singleton patterns for single field bags.

### LINKED ISSUE #1581: Correctly apply single field component bags
This behavior is _not_ specified in the UTS 35 skeleton matching algorithm as far as I can tell, but I have deduced it as follows:

1. If a skeleton has any extra fields, ignore it.
2. Either a) there is a skeleton match with a subset of the fields, or b) There is no skeleton match.

Given A:
1. Use the appendItems algorithm specified in UTS 35 to build up the full match.

Given B:
1. No skeleton matched, use the field directly as the pattern.
2. If there is a stand-alone version of the field, use the stand-alone version.

The work here is to fix the case where "B" is. A is required for append items support.

Here is the example of what ICU4C generates: https://github.com/gregtatum/spec-cpp/blob/5d577ed924a1f3aa019344011162e84fabf0a6f6/src/features/icu.cpp#L400-L517

### PR DESCRIPTION
**Pull request by mildgravitas**
Singleton field patterns are returned as-is if `prefer_matched_pattern = false` and either:
1. All matching patterns have extra symbols.
2. The matching pattern would differ from the field due to either:
  2.a. Textual/numeric differences which UTS 35 says should not be adjusted.
  2.b. Semantic differences (e.g. 'd' vs 'F'). We don't adjust these & UTS is unclear on the subject.

The `prefer_matched_pattern` constraint is for consistency with `CoarseHourCycle::apply_on_pattern` which shouldn't stray from existing patterns. Removing it does not yield any datagen differences however.

Concerning augmenting `BestSkeleton` with a new enum for this use case, it doesn't seem like the codebase would benefit from it:
 - outside of helpers.rs, all callers conflate `AllFieldsMatch` & `MissingOrExtraFields`. 
 - helpers.rs uses the distinction to check whether it should try processing date & time fields separately which doesn't apply to singleton inputs.
 
Fixes #1581

### CODE REVIEW

File: components/datetime/src/skeleton/helpers.rs [hunk 1]
```diff
@@ -424,6 +425,16 @@ pub fn get_best_available_format_pattern<'data>(
         }
     }
 
+    if !prefer_matched_pattern && closest_distance >= TEXT_VS_NUMERIC_DISTANCE {
+        if let [field] = fields {
```
Comment (gregtatum) [inline components/datetime/src/skeleton/helpers.rs:429]: Question: Should we check that the requested field length is actually 1 here? This would guard against potential logic errors in the implementation.

File: components/datetime/src/skeleton/helpers.rs [hunk 2]
```diff
@@ -424,6 +425,16 @@ pub fn get_best_available_format_pattern<'data>(
...
+            // A single field was requested and the best pattern either includes extra fields or can't be adjusted to match
```
Comment (gregtatum) [inline components/datetime/src/skeleton/helpers.rs:430]: Praise: Thanks for the documentation.

File: components/datetime/tests/fixtures/tests/components-partial-matches.json [hunk 3]
```diff
@@ -1,6 +1,6 @@
 [
     {
-        "description": "Partial match for m -> hm -> h:m a",
+        "description": "Singleton fields are returned directly if there are no singleton matches (m -> hm)",
```
Comment (gregtatum) [inline components/datetime/tests/fixtures/tests/components-partial-matches.json:3]: suggestion: It would be good to have a bit better code coverage here with:

* Additional locales
* Additional field types
* Additional field widths.

**Review by gregtatum — CHANGES_REQUESTED** [review]
Thanks for the fix! I'm only marking for changes for a bit better test coverage.

**Review by gregtatum — APPROVED** [review]
Thanks for addressing the suggestion!

**Review by zbraniecki — DISMISSED** [review]
can you add a test for hour singleton (for h11/12/23/24 scenarios)?

**Review by nordzilla — DISMISSED** [review]

**Comment by mildgravitas** [comment]
@zbraniecki: I've added hXX tests, they pass both before & after this PR.

**Review by zbraniecki — APPROVED** [review]
lgtm! Thank you!
