### PR TITLE
Fix tinywasm example

### LINKED ISSUE #3582: Re-enable tinywasm FFI CI
It gets stuck here:

```
...
2023-06-27T06:21:24.1339208Z cp target/wasm32-unknown-unknown/release/icu_capi_cdylib.wasm icu_capi.wasm
2023-06-27T06:21:24.1355342Z cargo run -p icu_datagen -- \
2023-06-27T06:21:24.1355873Z 	--keys-for-bin icu_capi.wasm \
2023-06-27T06:21:24.1356257Z 	--locales full \
2023-06-27T06:21:24.1356610Z 	--format blob \
2023-06-27T06:21:24.1357007Z 	--out data.postcard
2023-06-27T06:21:24.7096518Z     Finished dev [unoptimized + debuginfo] target(s) in 0.53s
2023-06-27T06:21:24.7154466Z      Running `/home/runner/work/icu4x/icu4x/target/debug/icu4x-datagen --keys-for-bin icu_capi.wasm --locales full --format blob --out data.postcard`
2023-06-27T09:18:34.1380351Z INFO  [icu_provider_blob::export::blob_exporter] Serializing blob to output stream...
2023-06-27T09:18:34.2128602Z rm -rf lib;
2023-06-27T09:18:34.2148391Z mkdir lib;
2023-06-27T09:18:34.2167144Z cp ../../include/* lib
...
```

The first commit exhibiting this behavior is https://github.com/unicode-org/icu4x/commit/c394c1c6c121e15b05aa7b0aa98826c0cf965694 but it's unclear why that would be at fault.

### PR DESCRIPTION
**Pull request by sffc**
Fixes #3582

Replaces #4121

### CODE REVIEW

File: ffi/capi/js/examples/tinywasm/Makefile [hunk 1]
```diff
@@ -33,8 +33,8 @@ target/wasm32-unknown-unknown/release/icu_capi_cdylib.wasm: FORCE
 		--target wasm32-unknown-unknown \
 		--release \
 		--package icu_capi_cdylib \
-		--no-default-features
-		--features buffer_provider,logging \
+		--no-default-features \
+		--features buffer_provider,logging,icu_capi/icu_decimal
```
Comment (robertbastian) [inline ffi/capi/js/examples/tinywasm/Makefile:37]: Enabling features on a dependency only works if the dependency is local, so this does not work as an example.

**Comment by sffc** [comment]
tinywasm is working in the ffi ci job; takes about 52 seconds. The job as a whole is failing because of the disk size error that is also on main.

```
2023-10-10T00:31:45.9396994Z [cargo-make] INFO - Running Task: test-tinywasm
2023-10-10T00:31:45.9420611Z Skipping test-wasm since it's slow https://github.com/unicode-org/icu4x/issues/3582 
2023-10-10T00:31:45.9461772Z rustup toolchain install nightly-2022-12-26
2023-10-10T00:31:46.0503636Z info: syncing channel updates for 'nightly-2022-12-26-x86_64-unknown-linux-gnu'
2023-10-10T00:31:46.0800448Z 
2023-10-10T00:31:46.0990653Z   nightly-2022-12-26-x86_64-unknown-linux-gnu unchanged - rustc 1.68.0-nightly (8dfb33954 2022-12-25)
2023-10-10T00:31:46.0991004Z 
2023-10-10T00:31:46.0996243Z info: checking for self-update
2023-10-10T00:31:46.1086612Z rustup component add rust-src --toolchain nightly-2022-12-26
2023-10-10T00:31:46.1953626Z info: component 'rust-src' is up to date
2023-10-10T00:31:46.1978362Z # Build the WASM library
2023-10-10T00:31:46.2000085Z RUSTFLAGS="-Cpanic=abort -Copt-level=s -C link-arg=-zstack-size=100000 -Clinker-plugin-lto -Ccodegen-units=1 -C linker=/__w/icu4x/icu4x/ffi/capi/js/examples/tinywasm//ld.py -C linker-flavor=wasm-ld" \
2023-10-10T00:31:46.2001158Z CARGO_TARGET_DIR="target" `# Special linker flags shouldn't overwrite the top-level target directory` \
2023-10-10T00:31:46.2001727Z cargo +nightly-2022-12-26 build \
2023-10-10T00:31:46.2002795Z 	-Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort \
2023-10-10T00:31:46.2003514Z 	--target wasm32-unknown-unknown \
2023-10-10T00:31:46.2003877Z 	--release \
2023-10-10T00:31:46.2004261Z 	--package icu_capi_cdylib \
2023-10-10T00:31:46.2004634Z 	--no-default-features \
2023-10-10T00:31:46.2005157Z 	--features buffer_provider,logging,icu_capi/icu_decimal
2023-10-10T00:31:46.7528031Z  Downloading crates ...
2023-10-10T00:31:46.9121402Z   Downloaded postcard v1.0.7
2023-10-10T00:31:46.9172664Z   Downloaded cobs v0.2.3
2023-10-10T00:31:47.0432289Z    Compiling compiler_builtins v0.1.85
2023-10-10T00:31:47.0453694Z    Compiling core v0.0.0 (/usr/local/rustup/toolchains/nightly-2022-12-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core)
2023-10-10T00:31:47.4363318Z    Compiling libc v0.2.138
2023-10-10T00:31:47.8991348Z    Compiling proc-macro2 v1.0.67
2023-10-10T00:31:48.3136308Z    Compiling cc v1.0.76
2023-10-10T00:31:49.5807598Z    Compiling unicode-ident v1.0.12
2023-10-10T00:31:49.7128822Z    Compiling unwind v0.0.0 (/usr/local/rustup/toolchains/nightly-2022-12-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/unwind)
2023-10-10T00:31:50.8945079Z    Compiling dlmalloc v0.2.3
2023-10-10T00:31:51.1367584Z    Compiling quote v1.0.33
2023-10-10T00:31:51.4823373Z    Compiling std v0.0.0 (/usr/local/rustup/toolchains/nightly-2022-12-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std)
2023-10-10T00:31:51.8121367Z    Compiling syn v2.0.37
2023-10-10T00:31:58.1978591Z    Compiling rustc-std-workspace-core v1.99.0 (/usr/local/rustup/toolchains/nightly-2022-12-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-core)
2023-10-10T00:31:58.5455599Z    Compiling serde_derive v1.0.188
2023-10-10T00:32:00.1311975Z    Compiling alloc v0.0.0 (/usr/local/rustup/toolchains/nightly-2022-12-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc)
2023-10-10T00:32:02.3708798Z    Compiling cfg-if v1.0.0
2023-10-10T00:32:02.4558297Z    Compiling rustc-std-workspace-alloc v1.99.0 (/usr/local/rustup/toolchains/nightly-2022-12-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-alloc)
2023-10-10T00:32:02.6191332Z    Compiling hashbrown v0.12.3
2023-10-10T00:32:03.1168392Z    Compiling std_detect v0.1.5 (/usr/local/rustup/toolchains/nightly-2022-12-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/stdarch/crates/std_detect)
2023-10-10T00:32:03.2390606Z    Compiling panic_abort v0.0.0 (/usr/local/rustup/toolchains/nightly-2022-12-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/panic_abort)
2023-10-10T00:32:03.2443082Z    Compiling rustc-demangle v0.1.21
2023-10-10T00:32:04.0613453Z    Compiling panic_unwind v0.0.0 (/usr/local/rustup/toolchains/nightly-2022-12-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/panic_unwind)
2023-10-10T00:32:04.1634391Z    Compiling unicode-xid v0.2.4
2023-10-10T00:32:04.2843888Z    Compiling synstructure v0.13.0
2023-10-10T00:32:05.0635304Z    Compiling serde v1.0.188
2023-10-10T00:32:05.4762421Z    Compiling zerofrom-derive v0.1.3 (/__w/icu4x/icu4x/utils/zerofrom/derive)
2023-10-10T00:32:08.1379353Z    Compiling proc_macro v0.0.0 (/usr/local/rustup/toolchains/nightly-2022-12-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/proc_macro)
2023-10-10T00:32:11.2621300Z    Compiling zerofrom v0.1.3 (/__w/icu4x/icu4x/utils/zerofrom)
2023-10-10T00:32:11.3991364Z    Compiling stable_deref_trait v1.2.0
2023-10-10T00:32:11.4860153Z    Compiling yoke-derive v0.7.2 (/__w/icu4x/icu4x/utils/yoke/derive)
2023-10-10T00:32:13.2417871Z    Compiling zerovec-derive v0.10.0 (/__w/icu4x/icu4x/utils/zerovec/derive)
2023-10-10T00:32:14.5308806Z    Compiling yoke v0.7.2 (/__w/icu4x/icu4x/utils/yoke)
2023-10-10T00:32:14.7300545Z    Compiling displaydoc v0.2.4
2023-10-10T00:32:14.9118218Z    Compiling zerovec v0.10.0 (/__w/icu4x/icu4x/utils/zerovec)
2023-10-10T00:32:15.7858723Z    Compiling writeable v0.5.3 (/__w/icu4x/icu4x/utils/writeable)
2023-10-10T00:32:15.9866851Z    Compiling litemap v0.7.1 (/__w/icu4x/icu4x/utils/litemap)
2023-10-10T00:32:16.2229389Z    Compiling tinystr v0.7.4 (/__w/icu4x/icu4x/utils/tinystr)
2023-10-10T00:32:16.4246528Z    Compiling cobs v0.2.3
2023-10-10T00:32:16.5660435Z    Compiling postcard v1.0.7
2023-10-10T00:32:16.6241924Z    Compiling icu_locid v1.3.2 (/__w/icu4x/icu4x/components/locid)
2023-10-10T00:32:16.9864935Z    Compiling log v0.4.20
2023-10-10T00:32:17.2198391Z    Compiling icu_provider_macros v1.3.2 (/__w/icu4x/icu4x/provider/macros)
2023-10-10T00:32:18.0196371Z    Compiling icu_provider v1.3.2 (/__w/icu4x/icu4x/provider/core)
2023-10-10T00:32:18.8391865Z    Compiling strck v0.1.2
2023-10-10T00:32:19.0023750Z    Compiling strck_ident v0.1.2
2023-10-10T00:32:19.1795218Z    Compiling ryu v1.0.15
2023-10-10T00:32:19.4051727Z    Compiling smallvec v1.11.1
2023-10-10T00:32:19.8830843Z    Compiling lazy_static v1.4.0
2023-10-10T00:32:19.9795837Z    Compiling fixed_decimal v0.5.4 (/__w/icu4x/icu4x/utils/fixed_decimal)
2023-10-10T00:32:20.4659826Z    Compiling icu_locid_transform v1.3.2 (/__w/icu4x/icu4x/components/locid_transform)
2023-10-10T00:32:22.2907550Z    Compiling diplomat_core v0.6.0
2023-10-10T00:32:23.0685528Z    Compiling icu_provider_adapters v1.3.2 (/__w/icu4x/icu4x/provider/adapters)
2023-10-10T00:32:23.2726607Z    Compiling icu_decimal v1.3.2 (/__w/icu4x/icu4x/components/decimal)
2023-10-10T00:32:23.5925104Z    Compiling icu_provider_blob v1.3.2 (/__w/icu4x/icu4x/provider/blob)
2023-10-10T00:32:24.5811649Z    Compiling diplomat-runtime v0.6.0
2023-10-10T00:32:24.6051408Z    Compiling diplomat v0.6.0
2023-10-10T00:32:25.4845369Z    Compiling icu_capi v1.3.2 (/__w/icu4x/icu4x/ffi/capi)
2023-10-10T00:32:27.5947187Z    Compiling icu_capi_cdylib v1.3.2 (/__w/icu4x/icu4x/ffi/capi_cdylib)
2023-10-10T00:32:30.7404756Z     Finished release [optimized] target(s) in 44.52s
2023-10-10T00:32:30.7581916Z cp target/wasm32-unknown-unknown/release/icu_capi_cdylib.wasm icu_capi.wasm
2023-10-10T00:32:30.7604100Z cargo run -p icu_datagen -- \
2023-10-10T00:32:30.7604627Z 	--keys-for-bin icu_capi.wasm \
2023-10-10T00:32:30.7605009Z 	--locales full \
2023-10-10T00:32:30.7605342Z 	--format blob \
2023-10-10T00:32:30.7605697Z 	--out data.postcard \
2023-10-10T00:32:30.7606036Z 	--overwrite
2023-10-10T00:32:31.9885863Z     Finished dev [unoptimized + debuginfo] target(s) in 1.17s
2023-10-10T00:32:31.9975002Z      Running `/__w/icu4x/icu4x/target/debug/icu4x-datagen --keys-for-bin icu_capi.wasm --locales full --format blob --out data.postcard --overwrite`
2023-10-10T00:32:32.0828574Z INFO  [icu_datagen::driver] Datagen configured with fallback mode Hybrid and these locales: ALL
2023-10-10T00:32:32.0904417Z INFO  [icu_datagen::driver] Generating key decimal/symbols@1
2023-10-10T00:32:37.6705891Z INFO  [icu_provider_blob::export::blob_exporter] Serializing blob to output stream...
2023-10-10T00:32:37.7723742Z rm -rf lib;
2023-10-10T00:32:37.7746915Z mkdir lib;
2023-10-10T00:32:37.7774747Z cp ../../include/* lib
2023-10-10T00:32:37.7976331Z total 136
2023-10-10T00:32:37.7977204Z -rwxr-xr-x 1 root root  1801 Oct 10 00:10 Makefile
2023-10-10T00:32:37.7977802Z -rw-r--r-- 1 root root    82 Oct 10 00:10 README.md
2023-10-10T00:32:37.7978512Z -rw-r--r-- 1 root root 11613 Oct 10 00:32 data.postcard
2023-10-10T00:32:37.7979250Z -rw-r--r-- 1 root root   489 Oct 10 00:10 delete_fetch.mjs
2023-10-10T00:32:37.7979953Z -rw-r--r-- 1 root root   320 Oct 10 00:10 diplomat.config.js
2023-10-10T00:32:37.7980858Z -rwxr-xr-x 1 root root 68499 Oct 10 00:32 icu_capi.wasm
2023-10-10T00:32:37.7981537Z -rwxr-xr-x 1 root root  1307 Oct 10 00:10 ld.py
2023-10-10T00:32:37.7982174Z drwxr-xr-x 2 root root 20480 Oct 10 00:32 lib
2023-10-10T00:32:37.7982827Z -rw-r--r-- 1 root root    49 Oct 10 00:10 package.json
2023-10-10T00:32:37.7983546Z drwxr-xr-x 4 root root  4096 Oct 10 00:32 target
2023-10-10T00:32:37.7984206Z -rw-r--r-- 1 root root  1025 Oct 10 00:10 tiny.mjs
2023-10-10T00:32:37.9221196Z Output is ১০,০০০.০৭
```

File: ffi/capi/js/examples/tinywasm/Makefile (hunk 1 above)
Comment (sffc) [reply ffi/capi/js/examples/tinywasm/Makefile:39]: Added a comment.

Comment (robertbastian) [reply ffi/capi/js/examples/tinywasm/Makefile:39]: "you should create your own cdylib crate" is not something that a non-Rust developer will be able to do. It wasn't required before, and it shouldn't be required now, we just need to set the same features as before: `--no-default-features --features buffer_provider,default_components[,logging]`.

File: ffi/capi/js/examples/tinywasm/delete_fetch.mjs [hunk 2]
```diff
@@ -0,0 +1,9 @@
+// This file is part of ICU4X. For terms of use, please see the file
+// called LICENSE at the top level of the ICU4X source tree
+// (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).
+
+// diplomat-wasm.mjs uses fetch when available, but fetch in Node.js is broken,
```
Comment (robertbastian) [inline ffi/capi/js/examples/tinywasm/delete_fetch.mjs:5]: Do you want to file diplomat issue? If this a problem in one of our examples, it will also be a problem for clients

File: tools/make/ffi.toml [hunk 3]
```diff
@@ -313,11 +313,11 @@ if "${ICU4X_BUILDING_WITH_FORCED_NIGHTLY}"
     echo "Skipping test-wasm since ICU4X_BUILDING_WITH_FORCED_NIGHTLY is set"
 else
     echo "Skipping test-wasm since it's slow https://github.com/unicode-org/icu4x/issues/3582"
```
Comment (robertbastian) [inline tools/make/ffi.toml:315]: delete

File: ffi/capi/js/examples/tinywasm/Makefile (hunk 1 above)
Comment (robertbastian) [reply ffi/capi/js/examples/tinywasm/Makefile:39]: Actually, lets just migrate this example to compiled data to use default features. It also reduces the size and adds fallback which is currently missing.

Comment (robertbastian) [reply ffi/capi/js/examples/tinywasm/Makefile:39]: https://github.com/robertbastian/icu4x/commit/7cec5203e484b774df900077544c928f8253d892

File: ffi/capi/js/examples/tinywasm/delete_fetch.mjs (hunk 2 above)
Comment (sffc) [reply ffi/capi/js/examples/tinywasm/delete_fetch.mjs:5]: Basically the same issue as https://github.com/rust-diplomat/diplomat/issues/283

File: ffi/capi/js/examples/tinywasm/Makefile (hunk 1 above)
Comment (sffc) [reply ffi/capi/js/examples/tinywasm/Makefile:39]: Okay but I prefer to merge the narrow fix first.

File: tools/make/ffi.toml (hunk 3 above)
Comment (sffc) [reply tools/make/ffi.toml]: Done

**Review by Manishearth — APPROVED** [review]

File: ffi/capi/js/examples/tinywasm/delete_fetch.mjs (hunk 2 above)
Comment (robertbastian) [reply ffi/capi/js/examples/tinywasm/delete_fetch.mjs:5]: Link to that then?

File: ffi/capi/js/examples/tinywasm/Makefile (hunk 1 above)
Comment (robertbastian) [reply ffi/capi/js/examples/tinywasm/Makefile:39]: The narrow fix would have been to use the features from my second comment, this actually changes the example
